import type { Player } from '@/types'

// Wails runtime types (will be generated by Wails)
declare global {
  interface Window {
    go: {
      app: {
        App: {
          GetCurrentPlayer: () => Promise<Player | null>;
          MediaTogglePlayPause: () => Promise<void>;
          MediaNext: () => Promise<void>;
          MediaPrevious: () => Promise<void>;
          MediaToggleShuffle: () => Promise<void>;
          MediaToggleRepeat: () => Promise<void>;
          MediaSetRating: (rating: number) => Promise<void>;
          MediaSeek: (position: number) => Promise<void>;
          MediaSetVolume: (volume: number) => Promise<void>;
          Quit: () => Promise<void>;
        };
      };
    };
    runtime: {
      EventsOn: (eventName: string, callback: (...args: unknown[]) => void) => () => void;
      EventsOff: (eventName: string) => void;
    };
  }
}

export {}
