import {
  onMounted,
  onUnmounted,
  ref,
} from 'vue'

import {
  defaultPlayer,
  type Player,
} from '@/types'

// Check if Wails runtime is available
const isWailsAvailable = () => typeof window !== 'undefined' && 'go' in window

// Wails runtime types (will be generated by Wails)
declare global {
  interface Window {
    go: {
      app: {
        App: {
          GetCurrentPlayer: () => Promise<Player | null>;
          MediaTogglePlayPause: () => Promise<void>;
          MediaNext: () => Promise<void>;
          MediaPrevious: () => Promise<void>;
          MediaToggleShuffle: () => Promise<void>;
          MediaToggleRepeat: () => Promise<void>;
          MediaSetRating: (rating: number) => Promise<void>;
          MediaSeek: (position: number) => Promise<void>;
        };
      };
    };
    runtime: {
      EventsOn: (eventName: string, callback: (...args: unknown[]) => void) => () => void;
      EventsOff: (eventName: string) => void;
    };
  }
}

export function useMediaPlayer() {
  const player = ref<Player>(defaultPlayer)
  const isConnected = ref(false)
  const error = ref<string | null>(null)

  let unsubscribe: (() => void) | null = null

  onMounted(() => {
    if (!isWailsAvailable()) {
      console.warn('Wails runtime not available, using mock data')
      // Mock data for development
      player.value = {
        ...defaultPlayer,
        title: 'GUNSHOT',
        artist: 'LYKKE LI',
        album: 'so sad so sexy',
        state: 0, // Playing
        position: 145,
        duration: 240,
      }
      isConnected.value = true
      return
    }

    // Subscribe to media updates
    unsubscribe = window.runtime.EventsOn('media:update', (...args: unknown[]) => {
      const data = args[0] as Player | undefined
      if (data) {
        player.value = data
        isConnected.value = true
      }
    })

    // Subscribe to errors
    window.runtime.EventsOn('error:port_busy', (...args: unknown[]) => {
      const msg = args[0] as string | undefined
      if (msg) error.value = msg
    })

    // Get initial player state
    window.go.app.App.GetCurrentPlayer().then((p) => {
      if (p) {
        player.value = p
        isConnected.value = true
      }
    })
  })

  onUnmounted(() => {
    if (unsubscribe) unsubscribe()
  })

  // Control methods
  const togglePlayPause = async () => {
    console.log('[useMediaPlayer] togglePlayPause called')
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaTogglePlayPause()
        console.log('[useMediaPlayer] MediaTogglePlayPause success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaTogglePlayPause error:', err)
      }
    }
  }

  const next = async () => {
    console.log('[useMediaPlayer] next called')
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaNext()
        console.log('[useMediaPlayer] MediaNext success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaNext error:', err)
      }
    }
  }

  const previous = async () => {
    console.log('[useMediaPlayer] previous called')
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaPrevious()
        console.log('[useMediaPlayer] MediaPrevious success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaPrevious error:', err)
      }
    }
  }

  const toggleShuffle = async () => {
    console.log('[useMediaPlayer] toggleShuffle called')
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaToggleShuffle()
        console.log('[useMediaPlayer] MediaToggleShuffle success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaToggleShuffle error:', err)
      }
    }
  }

  const toggleRepeat = async () => {
    console.log('[useMediaPlayer] toggleRepeat called')
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaToggleRepeat()
        console.log('[useMediaPlayer] MediaToggleRepeat success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaToggleRepeat error:', err)
      }
    }
  }

  const setRating = async (rating: number) => {
    console.log('[useMediaPlayer] setRating called:', rating)
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaSetRating(rating)
        console.log('[useMediaPlayer] MediaSetRating success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaSetRating error:', err)
      }
    }
  }

  const seek = async (position: number) => {
    console.log('[useMediaPlayer] seek called:', position)
    if (isWailsAvailable()) {
      try {
        await window.go.app.App.MediaSeek(position)
        console.log('[useMediaPlayer] MediaSeek success')
      }
      catch (err) {
        console.error('[useMediaPlayer] MediaSeek error:', err)
      }
    }
  }

  return {
    player,
    isConnected,
    error,
    togglePlayPause,
    next,
    previous,
    toggleShuffle,
    toggleRepeat,
    setRating,
    seek,
  }
}
