import {
  onMounted,
  onUnmounted,
  ref,
} from 'vue'

import {
  defaultPlayer,
  type Player,
} from '@/types'

// Check if Wails runtime is available
const isWailsAvailable = () => typeof window !== 'undefined' && 'go' in window

// Wails runtime types (will be generated by Wails)
declare global {
  interface Window {
    go: {
      app: {
        App: {
          GetCurrentPlayer: () => Promise<Player | null>;
          MediaTogglePlayPause: () => Promise<void>;
          MediaNext: () => Promise<void>;
          MediaPrevious: () => Promise<void>;
          MediaToggleShuffle: () => Promise<void>;
          MediaToggleRepeat: () => Promise<void>;
          MediaSetRating: (rating: number) => Promise<void>;
          MediaSeek: (position: number) => Promise<void>;
        };
      };
    };
    runtime: {
      EventsOn: (eventName: string, callback: (...args: unknown[]) => void) => () => void;
      EventsOff: (eventName: string) => void;
    };
  }
}

export function useMediaPlayer() {
  const player = ref<Player>(defaultPlayer)
  const isConnected = ref(false)
  const error = ref<string | null>(null)

  let unsubscribe: (() => void) | null = null

  onMounted(() => {
    if (!isWailsAvailable()) {
      console.warn('Wails runtime not available, using mock data')
      // Mock data for development
      player.value = {
        ...defaultPlayer,
        title: 'GUNSHOT',
        artist: 'LYKKE LI',
        album: 'so sad so sexy',
        state: 0, // Playing
        position: 145,
        duration: 240,
      }
      isConnected.value = true
      return
    }

    // Subscribe to media updates
    unsubscribe = window.runtime.EventsOn('media:update', (...args: unknown[]) => {
      const data = args[0] as Player | undefined
      if (data) {
        player.value = data
        isConnected.value = true
      }
    })

    // Subscribe to errors
    window.runtime.EventsOn('error:port_busy', (...args: unknown[]) => {
      const msg = args[0] as string | undefined
      if (msg) error.value = msg
    })

    // Get initial player state
    window.go.app.App.GetCurrentPlayer().then((p) => {
      if (p) {
        player.value = p
        isConnected.value = true
      }
    })
  })

  onUnmounted(() => {
    if (unsubscribe) unsubscribe()
  })

  // Control methods
  const togglePlayPause = async () => {
    if (isWailsAvailable()) await window.go.app.App.MediaTogglePlayPause()
  }

  const next = async () => {
    if (isWailsAvailable()) await window.go.app.App.MediaNext()
  }

  const previous = async () => {
    if (isWailsAvailable()) await window.go.app.App.MediaPrevious()
  }

  const toggleShuffle = async () => {
    if (isWailsAvailable()) await window.go.app.App.MediaToggleShuffle()
  }

  const toggleRepeat = async () => {
    if (isWailsAvailable()) await window.go.app.App.MediaToggleRepeat()
  }

  const setRating = async (rating: number) => {
    if (isWailsAvailable()) await window.go.app.App.MediaSetRating(rating)
  }

  const seek = async (position: number) => {
    if (isWailsAvailable()) await window.go.app.App.MediaSeek(position)
  }

  return {
    player,
    isConnected,
    error,
    togglePlayPause,
    next,
    previous,
    toggleShuffle,
    toggleRepeat,
    setRating,
    seek,
  }
}
