// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';

export function ChangeWNPPort(arg1:number):Promise<void>;

export function GetCurrentPlayer():Promise<media.Player>;

export function GetWNPPort():Promise<number>;

export function IsAutorunEnabled():Promise<boolean>;

export function IsWNPConnected():Promise<boolean>;

export function LoadWindowPosition():Promise<number|number>;

export function MediaNext():Promise<void>;

export function MediaPause():Promise<void>;

export function MediaPlay():Promise<void>;

export function MediaPrevious():Promise<void>;

export function MediaSeek(arg1:number):Promise<void>;

export function MediaSetRating(arg1:number):Promise<void>;

export function MediaSetVolume(arg1:number):Promise<void>;

export function MediaTogglePlayPause():Promise<void>;

export function MediaToggleRepeat():Promise<void>;

export function MediaToggleShuffle():Promise<void>;

export function SaveWindowPosition():Promise<void>;

export function SetAutorun(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
