// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeWNPPort(arg1) {
  return window['go']['app']['App']['ChangeWNPPort'](arg1);
}

export function GetCurrentPlayer() {
  return window['go']['app']['App']['GetCurrentPlayer']();
}

export function GetWNPPort() {
  return window['go']['app']['App']['GetWNPPort']();
}

export function IsAutorunEnabled() {
  return window['go']['app']['App']['IsAutorunEnabled']();
}

export function IsWNPConnected() {
  return window['go']['app']['App']['IsWNPConnected']();
}

export function LoadWindowPosition() {
  return window['go']['app']['App']['LoadWindowPosition']();
}

export function MediaNext() {
  return window['go']['app']['App']['MediaNext']();
}

export function MediaPause() {
  return window['go']['app']['App']['MediaPause']();
}

export function MediaPlay() {
  return window['go']['app']['App']['MediaPlay']();
}

export function MediaPrevious() {
  return window['go']['app']['App']['MediaPrevious']();
}

export function MediaSeek(arg1) {
  return window['go']['app']['App']['MediaSeek'](arg1);
}

export function MediaSetRating(arg1) {
  return window['go']['app']['App']['MediaSetRating'](arg1);
}

export function MediaSetVolume(arg1) {
  return window['go']['app']['App']['MediaSetVolume'](arg1);
}

export function MediaTogglePlayPause() {
  return window['go']['app']['App']['MediaTogglePlayPause']();
}

export function MediaToggleRepeat() {
  return window['go']['app']['App']['MediaToggleRepeat']();
}

export function MediaToggleShuffle() {
  return window['go']['app']['App']['MediaToggleShuffle']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function SaveWindowPosition() {
  return window['go']['app']['App']['SaveWindowPosition']();
}

export function SetAutorun(arg1) {
  return window['go']['app']['App']['SetAutorun'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}
